#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'

cookbook 'python'
cookbook 'postgresql'
cookbook "rvm",
    :git => 'https://github.com/fnichol/chef-rvm'
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
