#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'

cookbook 'apt'
cookbook 'python'
cookbook 'postgresql'
#cookbook 'bash_profile',
#   :git => 'https://github.com/kyleburton/chef-cookbooks/'
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
